config/routes.rb
Rails.application.routes.draw do
  resources :articles
root 'welcome#index'
get  'welcome/about', to: 'welcome#about'

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true, length: {miniumn: 3, maximum:50}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
  def about

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<div id="wrapper">
  <div id="main">
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
    <footer>&copy2016 BadgerTex.com</footer>
  </div>
</div>

app/views/articles/edit.html.erb
<div id="wrapper">
  <div id="main">
    <h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>
    <footer>&copy2016 BadgerTex.com</footer>
  </div>
</div>

app/views/articles/index.html.erb
  <div id="main">
<p id="notice"><%= notice %></p>

<h1>Listing Articles</h1>
   <nav><%= link_to "Home", root_path %>
  <%= link_to "About", welcome_about_path %>
  <%= link_to "Articles", articles_path %></nav>
    <hr>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>
    <footer>&copy2016 BadgerTex.com</footer>
  </div>

app/views/articles/new.html.erb
<div id="wrapper">
  <div id="main">
    <h1>New Article</h1>
   <nav><%= link_to "Home", root_path %>
  <%= link_to "About", welcome_about_path %>
  <%= link_to "Articles", articles_path %></nav>
    <hr>
<%= render 'form' %>

<%= link_to 'Back', articles_path %>

   
  </div>
</div>

app/views/articles/show.html.erb
<div id="main">

<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>
<br>
  <br>
  <footer>&copy2016 BadgerTex.com</footer>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/about.html.erb
  <div id="main">

       <h1>About</h1>
     <nav><%= link_to "Home", root_path %>
  <%= link_to "About", welcome_about_path %>
  <%= link_to "Articles", articles_path %></nav>
 <div id="left">
    <h4>Here is a little story about us</h4>

    <p>Congratulations - you just destroyed the Falcon. Some days you get the bear, and some days the bear gets you. Now we know what they mean by 'advanced' tactical training. About four years. I got tired of hearing how young I looked. You enjoyed that. When has justice ever been as simple as a rule book?</p>
    <h4>Lucas Ipsum Dolor</h4>
    <p>Lucas ipsum dolor sit amet valorum dat solo quinlan zev mimbanite jettster r5-d4 rex tsavong. Bail endor tapani ogemite. Plo mustafarian gank natasi dengar sifo-dyas. Rieekan bail lannik rukh jagged dunhausen celegian droch yoda. Hypori kota firmus bib darth draethos pellaeon omwati. Ord sabé gotal gordin gossam zannah nute. R5-d4 deliah antilles gora maul luke porkins bibble. Kathol y'bith darpa palpatine. Darpa ree-yees kaleesh plo piell. Melodie gallia darth jeremoch tyber fisto carlist frozian muun. </p>

  </div>
  <div id="right">
    <h4>Star Wars Rocks!</h4>
    <hr>
    <%= image_tag 'sw1.jpg' %>
    <%= image_tag 'sw2.pmg.jpg' %>

  </div>

<footer>&copy 2016 BadgerTex.com</footer>
</div>

app/views/welcome/index.html.erb
  <div id="main">

    <h1>Welcome to Badger &alpha;-Blog Application</h1>
  <nav><%= link_to "Home", root_path %>
  <%= link_to "About", welcome_about_path %>
  <%= link_to "Articles", articles_path %></nav>
    <hr>
    <h3>This is the humble beginnings of a Ruby Application</h3>
    <p>We shall see how the venutre goes as we proceed forward. That might've been one of the shortest assignments in the history of Starfleet. This is not about revenge. This is about justice. Damage report! Worf, It's better than music. It's jazz. I'm afraid I still don't understand, sir. Why don't we just give everybody a promotion and call it a night - 'Commander'?</p>
    <h3>Moving Forward</h3>
    <p>The Enterprise computer system is controlled by three primary main processor cores, cross-linked with a redundant melacortz ramistat, fourteen kiloquad interface modules. Worf, It's better than music. It's jazz. Computer, belay that order. and attack the Romulans. The look in your eyes, I recognize it. You used to have it for me. Wait a minute - you've been declared dead. You can't give orders around here. Computer, lights up! Damage report! Wouldn't that bring about chaos? You did exactly what you had to do. You considered all your options, you tried every alternative and then you made the hard choice. Mr. Worf, you do remember how to fire phasers? You bet I'm agitated! I may be surrounded by insanity, but I am not insane. You enjoyed that.</p>
 <br>
    <br>
    <br><footer>&copy 2016 BadgerTex.com</footer>
  </div>